### ISSUE TITLE
Review and hide UIs in the carbon console that have alternatives or deprecated

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#23097]
### Current Limitation

With the recent development like,
- A new tenant management UI onboarded to the new console
- A new XACML UI onboarded to the new console
- Deprecated the use of the registry along with improving features to avoid using registry internally
the respective UIs in the carbon console is not longer recommended to use.

### Suggested Improvement

Such UIs needs to be excluded in the carbon console as the default option.

### Version

7.1.0

**Comment by darshanasbg** [comment]
Fixed with,
- https://github.com/wso2/product-is/pull/23100

**Comment by darshanasbg** [comment]
> * [Hide entitlement UIs from carbon console #23105](https://github.com/wso2/product-is/pull/23105)

Above XACML UI hiding improvement would not be needed, if we are not providing `org.wso2.carbon.identity.entitlement.ui` & `org.wso2.carbon.policyeditor.ui` with the XACML connector.

**Comment by JeethJJ** [comment]
> Above XACML UI hiding improvement would not be needed, if we are not providing `org.wso2.carbon.identity.entitlement.ui` & `org.wso2.carbon.policyeditor.ui` with the XACML connector.

@darshanasbg regardless, we decided to hide the Entitlement section (XACML) from the management console since eventhough its only available after adding the connector, we still do not expect/recommend the user to use the MC. 

FYI : @DMHP

**Comment by darshanasbg** [comment]
> > Above XACML UI hiding improvement would not be needed, if we are not providing `org.wso2.carbon.identity.entitlement.ui` & `org.wso2.carbon.policyeditor.ui` with the XACML connector.
> 
> [@darshanasbg](https://github.com/darshanasbg) regardless, we decided to hide the Entitlement section (XACML) from the management console since eventhough its only available after adding the connector, we still do not expect/recommend the user to use the MC.
> 
> FYI : [@DMHP](https://github.com/DMHP)

@JeethJJ not clear what you meant.. Are you saying we need to include the change: https://github.com/wso2/product-is/pull/23105? Without that Entitlement section will be available in the MC once the connector is installed.

**Comment by JeethJJ** [comment]
> [@JeethJJ](https://github.com/JeethJJ) not clear what you meant.. Are you saying we need to include the change: [#23105](https://github.com/wso2/product-is/pull/23105)? Without that Entitlement section will be available in the MC once the connector is installed.

@darshanasbg Yes thats correct.
