### ISSUE TITLE
Move the OIDC discovery endpoint under the root issuer/.well-known/openid-configuration

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#3480]
According to the spec [1] the discovery endpoint should be located in the path <issuer>/.well-known/openid-configuration. 

OpenID Providers supporting Discovery MUST make a JSON document available at the path formed by concatenating the string /.well-known/openid-configuration to the Issuer.
 
Currently in IS server, the document is located in "oidcdiscovery/.well-known/openid-configuration".

[1] [https://openid.net/specs/openid-connect-discovery-1_0.html#IssuerDiscovery]

**Comment by pulasthi7** [comment]
@DMHP Is this fixed now with above PR?

**Comment by mxm-tr** [comment]
It appears to still occur on WSO2 5.11: the default oidc discovery endpoint is under https://<root-url>/oauth2/oidcdiscovery/.well-known/openid-configuration
