### ISSUE TITLE
 SCIM2 filter user by username returns duplicate results

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#3563]
(Original Issue title was: "2 mail attributes are saved in the userstore when the user is added from ask password feature")

Follow below steps to reproduce the issue.
- Change the userstore to JDBC
- Enable scim in the userstore manager.
- Change the username attribute to mail
- Enable ask password feature
- Add SCIM2 connector
- Create the user(jane@wso2.com) with username and email using ask password feature from management console.
- Try filtering user just added.

In SCIM 2.0 its returns same user twice.
Request:
`curl -v -k --user admin:admin https://localhost:9443/scim2/Users?filter=userName%20eq%20jane@wso2.com`

Response:
```
{  
   "totalResults":2,
   "startIndex":1,
   "itemsPerPage":2,
   "schemas":[  
      "urn:ietf:params:scim:api:messages:2.0:ListResponse"
   ],
   "Resources":[  
      {  
         "meta":{  
            "created":"2018-08-16T16:39:00Z",
            "lastModified":"2018-08-16T16:39:00Z",
            "resourceType":"User"
         },
         "id":"9e7fbb53-f7d9-4e19-95b4-cff271df86fd",
         "userName":"jane@wso2.com"
      },
      {  
         "meta":{  
            "created":"2018-08-16T16:39:00Z",
            "lastModified":"2018-08-16T16:39:00Z",
            "resourceType":"User"
         },
         "id":"9e7fbb53-f7d9-4e19-95b4-cff271df86fd",
         "userName":"jane@wso2.com"
      }
   ]
}
```
In SCIM 1.1 its returns correct output

Request:
`curl -v -k --user admin:admin https://localhost:9443/wso2/scim/Users?filter=userName%20eq%20jane@wso2.com`
Response:
```
{
    "totalResults": 1,
    "schemas": [
        "urn:scim:schemas:core:1.0"
    ],
    "Resources": [
        {
            "meta": {
                "created": "2018-08-16T16:39:00",
                "location": "https://localhost:9443/wso2/scim/Users/PRIMARY/jane@wso2.com",
                "lastModified": "2018-08-16T16:39:00"
            },
            "id": "9e7fbb53-f7d9-4e19-95b4-cff271df86fd",
            "userName": "PRIMARY/jane@wso2.com"
        }
    ]
}
```

When debugging, I noticed that below claims come to the JDBC userstore manager to persist.

- "urn:scim:schemas:core:1.0:userName" -> "user9@wso2.com"
- "urn:scim:schemas:core:1.0:id" -> "37895885-7016-4788-b83a-f5e5d7dfd54b"
- "http://wso2.org/claims/emailaddress" -> "user9@wso2.com"
- "urn:scim:schemas:core:1.0:meta.lastModified" -> "2018-08-13T16:32:41"
- "urn:scim:schemas:core:1.0:meta.created" -> "2018-08-13T16:32:41"

If we have enabled scim 2 connector, claims will be like below.

- "urn:ietf:params:scim:schemas:core:2.0:id" -> "f9f5f5bf-d8c2-47a9-aa6a-b10e55a8fcb4"
- "urn:ietf:params:scim:schemas:core:2.0:meta.created" -> "2018-08-13T16:16:09Z"
- "urn:ietf:params:scim:schemas:core:2.0:meta.lastModified" -> "2018-08-13T16:16:09Z"
- "urn:ietf:params:scim:schemas:core:2.0:meta.resourceType" -> "User"
- "http://wso2.org/claims/emailaddress" -> "user8@wso2.com"
- "urn:ietf:params:scim:schemas:core:2.0:User:userName" -> "user8@wso2.com"

As "http://wso2.org/claims/emailaddress" and "urn:scim:schemas:core:1.0:userName" (or "urn:ietf:params:scim:schemas:core:2.0:User:userName") maps to mail attribute, from the userstore manager level, it will persist 2 mail attributes for a single user.

Version: IS 5.3.0

**Comment by darshanasbg** [comment]
@madurangasiriwardena : What's the reason for setting username claim's mapped attribute value to mail?

**Comment by darshanasbg** [comment]
Fixed with: https://github.com/wso2/carbon-kernel/pull/1830

**Comment by madurangasiriwardena** [comment]
Reopening since this is still not working when the search is done any user attribute other than username

**Comment by madurangasiriwardena** [comment]
Created new issue to track the issue when search with any user attribute other than username.
https://github.com/wso2/product-is/issues/4228

Closing this issue since the issue described in the title is fixed.
